
 select * FROM customers;
  select * FROM orderdetails;
  select * FROM orders;
   select * FROM PRODUCTS;
 
 -- 1. List all customers and their cities
SELECT 
    c.CustomerID,
    c.Name,
    c.City
FROM Customers c
ORDER BY c.City, c.Name;

-- 2. Show the total number of products in each category
SELECT 
    p.Category,
    COUNT(*) AS total_products
FROM Products p
GROUP BY p.Category
ORDER BY total_products DESC;

-- 3.	Find the top 5 most expensive products.
SELECT 
    p.ProductID,
    p.ProductName,
    p.Category,
    p.Price
FROM Products p
ORDER BY p.Price DESC
LIMIT 5;


 -- 4. Show all orders placed in the last 90 days
SELECT 
    o.OrderID,
    o.CustomerID,
    o.OrderDate
FROM Orders o
WHERE o.OrderDate >= CURDATE() - INTERVAL 90 DAY
ORDER BY o.OrderDate DESC;

-- 5.	Find the total revenue generated by each product.
select p.ProductID,
ProductName,
Category, 
round(sum(p.price * od.Quantity),0) as Revenue
from products p 
join orderdetails od on 
p.ProductID= od.ProductID
group by ProductID, ProductName, Category
order by revenue DESC;

-- 6.	Show the customer who placed the highest number of orders.
SELECT c.CustomerID, c.Name,
count(o.OrderID) as high
from customers c
join orders o on
c.CustomerID= o.CustomerID
group by CustomerID
order by high desc
limit 1;


-- 7.	Find the average order value per customer.
select c.CustomerID, c.Name,
avg(o.OrderID) as avg_order
from customers c
join orders o 
on c.CustomerID = o.CustomerID
group by c.CustomerID
order by avg_order desc;


-- 8.	Show the total quantity of products sold per category.
select p.Category,
sum(od.Quantity) total
from products p
join orderdetails od
on p.ProductID=od.ProductID
group by p.Category
order by total  desc;

-- 9.	List customers who bought more than 10 items in total.

SELECT 
    c.customerID,
    c.Name,
    SUM(od.quantity) AS total_items
FROM customers c
JOIN orders o 
    ON c.CustomerID = o.CustomerID
JOIN orderdetails od 
    ON o.OrderID = od.OrderID
GROUP BY c.customerID, c.Name
HAVING SUM(od.quantity) > 10
ORDER BY total_items DESC;


--  10.	Show monthly sales totals for 2025.
select MONTHNAME(o.orderDate) AS month_name,
    MONTH(o.orderDate) AS month_number,
sum(p.Price) as total
from orders o
join products p
where year(orderdate) = 2025
GROUP BY MONTHNAME(o.orderDate), MONTH(o.orderDate)
order by month_number asc;



