-- ============================================================
--  SQL PRACTICE QUESTIONS & ANSWERS
--  Database: ecommerce_practice
--  50 Questions across 5 difficulty levels
-- ============================================================
-- HOW TO USE:
--   1. Import ecommerce_db.sql into your MySQL app first
--   2. Run:  USE ecommerce_practice;
--   3. Try each question before looking at the answer!
-- ============================================================


-- ════════════════════════════════════════════════════════════
-- LEVEL 1 — BEGINNER  (Questions 1–10)
-- Basic SELECT, WHERE, ORDER BY, LIMIT
-- ════════════════════════════════════════════════════════════

-- Q1. List all customers from Lagos.
-- ANSWER:
SELECT *
FROM customers
WHERE city = 'Lagos';

-- ─────────────────────────────────────────────────────────────

-- Q2. Show the top 5 most expensive products (name and price).
-- ANSWER:
SELECT name, price
FROM products
ORDER BY price DESC
LIMIT 5;

-- ─────────────────────────────────────────────────────────────

-- Q3. How many customers are registered in total?
-- ANSWER:
SELECT COUNT(*) AS total_customers
FROM customers;

-- ─────────────────────────────────────────────────────────────

-- Q4. List all products in the 'Phones & Tablets' category.
--     (Hint: join products to categories)
-- ANSWER:
SELECT p.name, p.price, p.brand
FROM products p
JOIN categories c ON c.category_id = p.category_id
WHERE c.name = 'Phones & Tablets'
ORDER BY p.price DESC;

-- ─────────────────────────────────────────────────────────────

-- Q5. Show all orders with status 'cancelled'.
-- ANSWER:
SELECT order_id, customer_id, order_date, shipping_city
FROM orders
WHERE status = 'cancelled';

-- ─────────────────────────────────────────────────────────────

-- Q6. What is the average product price across the entire catalogue?
-- ANSWER:
SELECT ROUND(AVG(price), 2) AS avg_price
FROM products;

-- ─────────────────────────────────────────────────────────────

-- Q7. List all distinct cities that customers come from, sorted A–Z.
-- ANSWER:
SELECT DISTINCT city
FROM customers
ORDER BY city;

-- ─────────────────────────────────────────────────────────────

-- Q8. Show all female customers born after 1995.
-- ANSWER:
SELECT first_name, last_name, email, birthdate
FROM customers
WHERE gender = 'Female'
  AND birthdate > '1995-12-31'
ORDER BY birthdate;

-- ─────────────────────────────────────────────────────────────

-- Q9. Which products have fewer than 50 units in stock?
-- ANSWER:
SELECT name, stock_qty, brand
FROM products
WHERE stock_qty < 50
ORDER BY stock_qty;

-- ─────────────────────────────────────────────────────────────

-- Q10. Show all orders placed in 2024, ordered by most recent first.
-- ANSWER:
SELECT order_id, customer_id, order_date, status
FROM orders
WHERE YEAR(order_date) = 2024
ORDER BY order_date DESC;


-- ════════════════════════════════════════════════════════════
-- LEVEL 2 — ELEMENTARY  (Questions 11–20)
-- Aggregation, GROUP BY, HAVING, JOINs
-- ════════════════════════════════════════════════════════════

-- Q11. How many orders has each customer placed? Show customer name and count,
--      ordered by most orders first.
-- ANSWER:
SELECT CONCAT(c.first_name,' ',c.last_name) AS customer_name,
       COUNT(o.order_id) AS total_orders
FROM customers c
LEFT JOIN orders o ON o.customer_id = c.customer_id
GROUP BY c.customer_id, customer_name
ORDER BY total_orders DESC;

-- ─────────────────────────────────────────────────────────────

-- Q12. What is the total revenue generated by each product category?
-- ANSWER:
SELECT cat.name AS category,
       SUM(oi.quantity * oi.unit_price) AS total_revenue
FROM order_items oi
JOIN products p   ON p.product_id   = oi.product_id
JOIN categories cat ON cat.category_id = p.category_id
JOIN orders o     ON o.order_id     = oi.order_id
WHERE o.status NOT IN ('cancelled','returned')
GROUP BY cat.category_id, category
ORDER BY total_revenue DESC;

-- ─────────────────────────────────────────────────────────────

-- Q13. Find all customers who have placed more than 2 orders.
-- ANSWER:
SELECT CONCAT(c.first_name,' ',c.last_name) AS customer_name,
       COUNT(o.order_id) AS order_count
FROM customers c
JOIN orders o ON o.customer_id = c.customer_id
GROUP BY c.customer_id, customer_name
HAVING COUNT(o.order_id) > 2
ORDER BY order_count DESC;

-- ─────────────────────────────────────────────────────────────

-- Q14. What is the total amount paid via each payment method?
-- ANSWER:
SELECT method,
       COUNT(*)       AS transaction_count,
       SUM(amount)    AS total_amount
FROM payments
WHERE status = 'successful'
GROUP BY method
ORDER BY total_amount DESC;

-- ─────────────────────────────────────────────────────────────

-- Q15. Show the average rating for each product that has at least one review.
--      Display product name, average rating, and number of reviews.
-- ANSWER:
SELECT p.name AS product_name,
       ROUND(AVG(r.rating), 2) AS avg_rating,
       COUNT(r.review_id)      AS review_count
FROM products p
JOIN reviews r ON r.product_id = p.product_id
GROUP BY p.product_id, product_name
ORDER BY avg_rating DESC;

-- ─────────────────────────────────────────────────────────────

-- Q16. Which shipping cities received the most orders?
--      Show the top 10.
-- ANSWER:
SELECT shipping_city,
       COUNT(*) AS orders_shipped
FROM orders
GROUP BY shipping_city
ORDER BY orders_shipped DESC
LIMIT 10;

-- ─────────────────────────────────────────────────────────────

-- Q17. Calculate total sales (revenue) per year.
-- ANSWER:
SELECT YEAR(o.order_date)              AS sales_year,
       COUNT(DISTINCT o.order_id)      AS total_orders,
       SUM(oi.quantity * oi.unit_price) AS total_revenue
FROM orders o
JOIN order_items oi ON oi.order_id = o.order_id
WHERE o.status NOT IN ('cancelled','returned')
GROUP BY sales_year
ORDER BY sales_year;

-- ─────────────────────────────────────────────────────────────

-- Q18. List products that have NEVER been ordered.
-- ANSWER:
SELECT p.product_id, p.name, p.price
FROM products p
LEFT JOIN order_items oi ON oi.product_id = p.product_id
WHERE oi.item_id IS NULL;

-- ─────────────────────────────────────────────────────────────

-- Q19. Show the top 5 best-selling products by total units sold.
-- ANSWER:
SELECT p.name       AS product_name,
       SUM(oi.quantity) AS total_units_sold
FROM products p
JOIN order_items oi ON oi.product_id = p.product_id
JOIN orders o       ON o.order_id    = oi.order_id
WHERE o.status NOT IN ('cancelled','returned')
GROUP BY p.product_id, product_name
ORDER BY total_units_sold DESC
LIMIT 5;

-- ─────────────────────────────────────────────────────────────

-- Q20. What percentage of orders were delivered successfully vs other statuses?
-- ANSWER:
SELECT status,
       COUNT(*) AS order_count,
       ROUND(COUNT(*) * 100.0 / (SELECT COUNT(*) FROM orders), 2) AS percentage
FROM orders
GROUP BY status
ORDER BY order_count DESC;


-- ════════════════════════════════════════════════════════════
-- LEVEL 3 — INTERMEDIATE  (Questions 21–30)
-- Subqueries, CTEs, window functions, date functions
-- ════════════════════════════════════════════════════════════

-- Q21. Find the single highest-value order (by subtotal before shipping).
--      Show order id, customer name, and subtotal.
-- ANSWER:
SELECT o.order_id,
       CONCAT(c.first_name,' ',c.last_name) AS customer_name,
       SUM(oi.quantity * oi.unit_price)     AS subtotal
FROM orders o
JOIN customers c   ON c.customer_id = o.customer_id
JOIN order_items oi ON oi.order_id  = o.order_id
GROUP BY o.order_id, customer_name
ORDER BY subtotal DESC
LIMIT 1;

-- ─────────────────────────────────────────────────────────────

-- Q22. For each customer, show their most recent order date and the status
--      of that order.
-- ANSWER:
SELECT c.customer_id,
       CONCAT(c.first_name,' ',c.last_name) AS customer_name,
       MAX(o.order_date)                    AS last_order_date,
       o.status
FROM customers c
JOIN orders o ON o.customer_id = c.customer_id
WHERE o.order_date = (
    SELECT MAX(o2.order_date)
    FROM orders o2
    WHERE o2.customer_id = c.customer_id
)
GROUP BY c.customer_id, customer_name, o.status
ORDER BY last_order_date DESC;

-- ─────────────────────────────────────────────────────────────

-- Q23. Using a CTE, find customers whose total spending exceeds ₦2,000,000.
-- ANSWER:
WITH customer_spending AS (
    SELECT c.customer_id,
           CONCAT(c.first_name,' ',c.last_name) AS customer_name,
           SUM(oi.quantity * oi.unit_price)     AS total_spent
    FROM customers c
    JOIN orders o      ON o.customer_id  = c.customer_id
    JOIN order_items oi ON oi.order_id   = o.order_id
    WHERE o.status NOT IN ('cancelled','returned')
    GROUP BY c.customer_id, customer_name
)
SELECT *
FROM customer_spending
WHERE total_spent > 2000000
ORDER BY total_spent DESC;

-- ─────────────────────────────────────────────────────────────

-- Q24. Calculate gross profit margin (%) for each product category.
--      Profit Margin = (Revenue - Cost) / Revenue * 100
-- ANSWER:
SELECT cat.name AS category,
       SUM(oi.quantity * oi.unit_price)         AS revenue,
       SUM(oi.quantity * p.cost)                AS total_cost,
       ROUND(
           (SUM(oi.quantity * oi.unit_price) - SUM(oi.quantity * p.cost))
           / SUM(oi.quantity * oi.unit_price) * 100, 2
       ) AS profit_margin_pct
FROM order_items oi
JOIN products p      ON p.product_id    = oi.product_id
JOIN categories cat  ON cat.category_id = p.category_id
JOIN orders o        ON o.order_id      = oi.order_id
WHERE o.status NOT IN ('cancelled','returned')
GROUP BY cat.category_id, category
ORDER BY profit_margin_pct DESC;

-- ─────────────────────────────────────────────────────────────

-- Q25. Show monthly revenue for the year 2023.
-- ANSWER:
SELECT DATE_FORMAT(o.order_date, '%Y-%m') AS month,
       COUNT(DISTINCT o.order_id)         AS orders,
       SUM(oi.quantity * oi.unit_price)   AS revenue
FROM orders o
JOIN order_items oi ON oi.order_id = o.order_id
WHERE YEAR(o.order_date) = 2023
  AND o.status NOT IN ('cancelled','returned')
GROUP BY month
ORDER BY month;

-- ─────────────────────────────────────────────────────────────

-- Q26. Rank all products by total revenue using a window function.
-- ANSWER:
SELECT p.name AS product_name,
       cat.name AS category,
       SUM(oi.quantity * oi.unit_price) AS revenue,
       RANK() OVER (ORDER BY SUM(oi.quantity * oi.unit_price) DESC) AS revenue_rank
FROM products p
JOIN categories cat  ON cat.category_id = p.category_id
JOIN order_items oi  ON oi.product_id   = p.product_id
JOIN orders o        ON o.order_id      = oi.order_id
WHERE o.status NOT IN ('cancelled','returned')
GROUP BY p.product_id, product_name, category
ORDER BY revenue_rank;

-- ─────────────────────────────────────────────────────────────

-- Q27. Find customers who have placed orders but never left a review.
-- ANSWER:
SELECT DISTINCT c.customer_id,
       CONCAT(c.first_name,' ',c.last_name) AS customer_name,
       c.email
FROM customers c
JOIN orders o ON o.customer_id = c.customer_id
WHERE c.customer_id NOT IN (
    SELECT DISTINCT customer_id FROM reviews
)
ORDER BY customer_name;

-- ─────────────────────────────────────────────────────────────

-- Q28. For each product category, show the top-selling product by revenue
--      using a correlated subquery or window function.
-- ANSWER:
WITH ranked AS (
    SELECT
        cat.name                         AS category,
        p.name                           AS product_name,
        SUM(oi.quantity * oi.unit_price) AS revenue,
        RANK() OVER (
            PARTITION BY cat.category_id
            ORDER BY SUM(oi.quantity * oi.unit_price) DESC
        ) AS rnk
    FROM products p
    JOIN categories cat  ON cat.category_id = p.category_id
    JOIN order_items oi  ON oi.product_id   = p.product_id
    JOIN orders o        ON o.order_id      = oi.order_id
    WHERE o.status NOT IN ('cancelled','returned')
    GROUP BY cat.category_id, category, p.product_id, product_name
)
SELECT category, product_name, revenue
FROM ranked
WHERE rnk = 1
ORDER BY revenue DESC;

-- ─────────────────────────────────────────────────────────────

-- Q29. Calculate the average number of days between a customer's first
--      and most recent order.
-- ANSWER:
SELECT c.customer_id,
       CONCAT(c.first_name,' ',c.last_name) AS customer_name,
       COUNT(o.order_id)                    AS total_orders,
       MIN(o.order_date)                    AS first_order,
       MAX(o.order_date)                    AS last_order,
       DATEDIFF(MAX(o.order_date), MIN(o.order_date)) AS days_as_customer
FROM customers c
JOIN orders o ON o.customer_id = c.customer_id
GROUP BY c.customer_id, customer_name
HAVING COUNT(o.order_id) > 1
ORDER BY days_as_customer DESC;

-- ─────────────────────────────────────────────────────────────

-- Q30. Show a running total of revenue by order date (cumulative revenue over time).
-- ANSWER:
SELECT
    DATE(o.order_date)                    AS order_date,
    SUM(oi.quantity * oi.unit_price)      AS daily_revenue,
    SUM(SUM(oi.quantity * oi.unit_price))
        OVER (ORDER BY DATE(o.order_date)) AS cumulative_revenue
FROM orders o
JOIN order_items oi ON oi.order_id = o.order_id
WHERE o.status NOT IN ('cancelled','returned')
GROUP BY DATE(o.order_date)
ORDER BY order_date;


-- ════════════════════════════════════════════════════════════
-- LEVEL 4 — ADVANCED  (Questions 31–40)
-- Complex multi-table queries, pivoting, advanced analytics
-- ════════════════════════════════════════════════════════════

-- Q31. Identify repeat customers: customers who ordered in BOTH 2022 and 2023.
-- ANSWER:
SELECT c.customer_id,
       CONCAT(c.first_name,' ',c.last_name) AS customer_name
FROM customers c
WHERE c.customer_id IN (
    SELECT customer_id FROM orders WHERE YEAR(order_date) = 2022
)
AND c.customer_id IN (
    SELECT customer_id FROM orders WHERE YEAR(order_date) = 2023
)
ORDER BY customer_name;

-- ─────────────────────────────────────────────────────────────

-- Q32. Calculate Customer Lifetime Value (CLV) = total revenue per customer,
--      and segment them as: 'VIP' (>2M), 'Regular' (500k–2M), 'Occasional' (<500k).
-- ANSWER:
WITH clv AS (
    SELECT
        c.customer_id,
        CONCAT(c.first_name,' ',c.last_name) AS customer_name,
        SUM(oi.quantity * oi.unit_price)     AS lifetime_value
    FROM customers c
    JOIN orders o      ON o.customer_id = c.customer_id
    JOIN order_items oi ON oi.order_id  = o.order_id
    WHERE o.status NOT IN ('cancelled','returned')
    GROUP BY c.customer_id, customer_name
)
SELECT customer_name,
       lifetime_value,
       CASE
           WHEN lifetime_value > 2000000  THEN 'VIP'
           WHEN lifetime_value >= 500000  THEN 'Regular'
           ELSE 'Occasional'
       END AS segment
FROM clv
ORDER BY lifetime_value DESC;

-- ─────────────────────────────────────────────────────────────

-- Q33. Find products that appear together in orders most frequently
--      (product affinity / market basket). Show top 10 pairs.
-- ANSWER:
SELECT
    p1.name AS product_1,
    p2.name AS product_2,
    COUNT(*) AS times_bought_together
FROM order_items oi1
JOIN order_items oi2 ON oi2.order_id   = oi1.order_id
                     AND oi2.product_id > oi1.product_id
JOIN products p1 ON p1.product_id = oi1.product_id
JOIN products p2 ON p2.product_id = oi2.product_id
GROUP BY p1.product_id, p1.name, p2.product_id, p2.name
ORDER BY times_bought_together DESC
LIMIT 10;

-- ─────────────────────────────────────────────────────────────

-- Q34. Calculate month-over-month revenue growth (%) for 2023.
-- ANSWER:
WITH monthly AS (
    SELECT DATE_FORMAT(o.order_date,'%Y-%m') AS month,
           SUM(oi.quantity * oi.unit_price)  AS revenue
    FROM orders o
    JOIN order_items oi ON oi.order_id = o.order_id
    WHERE YEAR(o.order_date) = 2023
      AND o.status NOT IN ('cancelled','returned')
    GROUP BY month
)
SELECT month,
       revenue,
       LAG(revenue) OVER (ORDER BY month) AS prev_month_revenue,
       ROUND(
           (revenue - LAG(revenue) OVER (ORDER BY month))
           / LAG(revenue) OVER (ORDER BY month) * 100, 2
       ) AS mom_growth_pct
FROM monthly
ORDER BY month;

-- ─────────────────────────────────────────────────────────────

-- Q35. Determine stock risk: products where stock_qty is below
--      the average monthly sales volume (risk of stockout).
-- ANSWER:
WITH sales_rate AS (
    SELECT
        p.product_id,
        p.name,
        p.stock_qty,
        SUM(oi.quantity) AS total_sold,
        COUNT(DISTINCT DATE_FORMAT(o.order_date,'%Y-%m')) AS months_active,
        ROUND(SUM(oi.quantity) /
              COUNT(DISTINCT DATE_FORMAT(o.order_date,'%Y-%m')), 1) AS avg_monthly_sales
    FROM products p
    JOIN order_items oi ON oi.product_id = p.product_id
    JOIN orders o       ON o.order_id    = oi.order_id
    WHERE o.status NOT IN ('cancelled','returned')
    GROUP BY p.product_id, p.name, p.stock_qty
)
SELECT product_id, name, stock_qty, avg_monthly_sales,
       ROUND(stock_qty / avg_monthly_sales, 1) AS months_of_stock_remaining
FROM sales_rate
WHERE stock_qty < avg_monthly_sales
ORDER BY months_of_stock_remaining;

-- ─────────────────────────────────────────────────────────────

-- Q36. Create a pivot-style report: total revenue by category for each
--      year (2022, 2023, 2024) in one row per category.
-- ANSWER:
SELECT cat.name AS category,
       SUM(CASE WHEN YEAR(o.order_date) = 2022 THEN oi.quantity * oi.unit_price ELSE 0 END) AS revenue_2022,
       SUM(CASE WHEN YEAR(o.order_date) = 2023 THEN oi.quantity * oi.unit_price ELSE 0 END) AS revenue_2023,
       SUM(CASE WHEN YEAR(o.order_date) = 2024 THEN oi.quantity * oi.unit_price ELSE 0 END) AS revenue_2024
FROM order_items oi
JOIN products p     ON p.product_id    = oi.product_id
JOIN categories cat ON cat.category_id = p.category_id
JOIN orders o       ON o.order_id      = oi.order_id
WHERE o.status NOT IN ('cancelled','returned')
GROUP BY cat.category_id, category
ORDER BY (revenue_2022 + revenue_2023 + revenue_2024) DESC;

-- ─────────────────────────────────────────────────────────────

-- Q37. Find the cohort retention: of customers who first ordered in 2022,
--      what percentage returned to order in 2023?
-- ANSWER:
WITH cohort_2022 AS (
    SELECT DISTINCT customer_id
    FROM orders
    WHERE YEAR(order_date) = 2022
),
returned_2023 AS (
    SELECT DISTINCT o.customer_id
    FROM orders o
    JOIN cohort_2022 c ON c.customer_id = o.customer_id
    WHERE YEAR(o.order_date) = 2023
)
SELECT
    COUNT(DISTINCT cohort_2022.customer_id) AS cohort_size,
    COUNT(DISTINCT returned_2023.customer_id) AS returned_in_2023,
    ROUND(
        COUNT(DISTINCT returned_2023.customer_id) * 100.0
        / COUNT(DISTINCT cohort_2022.customer_id), 2
    ) AS retention_rate_pct
FROM cohort_2022
LEFT JOIN returned_2023 ON returned_2023.customer_id = cohort_2022.customer_id;

-- ─────────────────────────────────────────────────────────────

-- Q38. For each customer, calculate the gap (in days) between consecutive orders
--      using window functions, and find the average gap per customer.
-- ANSWER:
WITH order_gaps AS (
    SELECT
        customer_id,
        order_date,
        LAG(order_date) OVER (PARTITION BY customer_id ORDER BY order_date) AS prev_order_date,
        DATEDIFF(order_date,
            LAG(order_date) OVER (PARTITION BY customer_id ORDER BY order_date)
        ) AS days_since_last_order
    FROM orders
)
SELECT
    c.customer_id,
    CONCAT(c.first_name,' ',c.last_name) AS customer_name,
    ROUND(AVG(og.days_since_last_order), 1) AS avg_days_between_orders
FROM customers c
JOIN order_gaps og ON og.customer_id = c.customer_id
WHERE og.days_since_last_order IS NOT NULL
GROUP BY c.customer_id, customer_name
ORDER BY avg_days_between_orders;

-- ─────────────────────────────────────────────────────────────

-- Q39. Find the top 3 revenue-contributing products within each category
--      (use dense_rank window function).
-- ANSWER:
WITH product_rev AS (
    SELECT
        cat.name                         AS category,
        p.name                           AS product_name,
        SUM(oi.quantity * oi.unit_price) AS revenue,
        DENSE_RANK() OVER (
            PARTITION BY cat.category_id
            ORDER BY SUM(oi.quantity * oi.unit_price) DESC
        ) AS dr
    FROM products p
    JOIN categories cat  ON cat.category_id = p.category_id
    JOIN order_items oi  ON oi.product_id   = p.product_id
    JOIN orders o        ON o.order_id      = oi.order_id
    WHERE o.status NOT IN ('cancelled','returned')
    GROUP BY cat.category_id, category, p.product_id, product_name
)
SELECT category, product_name, revenue, dr AS rank_in_category
FROM product_rev
WHERE dr <= 3
ORDER BY category, dr;

-- ─────────────────────────────────────────────────────────────

-- Q40. Build a full customer RFM (Recency, Frequency, Monetary) report.
--      R = days since last order, F = total orders, M = total spend.
--      Score each dimension 1-4 (4 = best) and compute RFM total score.
-- ANSWER:
WITH rfm_raw AS (
    SELECT
        c.customer_id,
        CONCAT(c.first_name,' ',c.last_name)  AS customer_name,
        DATEDIFF(CURDATE(), MAX(o.order_date)) AS recency_days,
        COUNT(DISTINCT o.order_id)             AS frequency,
        SUM(oi.quantity * oi.unit_price)       AS monetary
    FROM customers c
    JOIN orders o       ON o.customer_id = c.customer_id
    JOIN order_items oi ON oi.order_id   = o.order_id
    WHERE o.status NOT IN ('cancelled','returned')
    GROUP BY c.customer_id, customer_name
),
rfm_scored AS (
    SELECT *,
        NTILE(4) OVER (ORDER BY recency_days DESC)  AS r_score,  -- lower days = higher score
        NTILE(4) OVER (ORDER BY frequency)          AS f_score,
        NTILE(4) OVER (ORDER BY monetary)           AS m_score
    FROM rfm_raw
)
SELECT customer_name,
       recency_days,
       frequency,
       monetary,
       r_score, f_score, m_score,
       (r_score + f_score + m_score) AS rfm_total,
       CASE
           WHEN (r_score + f_score + m_score) >= 10 THEN 'Champion'
           WHEN (r_score + f_score + m_score) >= 7  THEN 'Loyal'
           WHEN (r_score + f_score + m_score) >= 5  THEN 'Potential'
           ELSE 'At Risk'
       END AS customer_segment
FROM rfm_scored
ORDER BY rfm_total DESC;


-- ════════════════════════════════════════════════════════════
-- LEVEL 5 — EXPERT  (Questions 41–50)
-- Stored procedures, views, optimization, advanced analytics
-- ════════════════════════════════════════════════════════════

-- Q41. Create a stored procedure that accepts a category name and returns
--      the total revenue, total units sold, and average product rating.
-- ANSWER:
DELIMITER $$
CREATE PROCEDURE GetCategoryStats(IN p_category VARCHAR(100))
BEGIN
    SELECT
        cat.name                             AS category,
        SUM(oi.quantity * oi.unit_price)     AS total_revenue,
        SUM(oi.quantity)                     AS total_units_sold,
        ROUND(AVG(r.rating), 2)              AS avg_rating
    FROM categories cat
    JOIN products p     ON p.category_id    = cat.category_id
    LEFT JOIN order_items oi ON oi.product_id = p.product_id
    LEFT JOIN orders o       ON o.order_id    = oi.order_id
                             AND o.status NOT IN ('cancelled','returned')
    LEFT JOIN reviews r      ON r.product_id  = p.product_id
    WHERE cat.name = p_category
    GROUP BY cat.name;
END$$
DELIMITER ;
-- Usage: CALL GetCategoryStats('Electronics');

-- ─────────────────────────────────────────────────────────────

-- Q42. Write a query to detect potential duplicate customer accounts
--      (same first name, last name, and city but different emails).
-- ANSWER:
SELECT c1.customer_id AS id_1,
       c1.email       AS email_1,
       c2.customer_id AS id_2,
       c2.email       AS email_2,
       c1.first_name, c1.last_name, c1.city
FROM customers c1
JOIN customers c2
    ON  c1.first_name = c2.first_name
    AND c1.last_name  = c2.last_name
    AND c1.city       = c2.city
    AND c1.customer_id < c2.customer_id;

-- ─────────────────────────────────────────────────────────────

-- Q43. Create a view that shows each order with all line items summarised —
--      customer name, order date, status, item count, subtotal, shipping, discount, grand total.
--      Then query it to show all VIP-tier orders (grand total > ₦1.5M).
-- ANSWER:
-- (View 'vw_order_summary' already created in ecommerce_db.sql)
-- Query:
SELECT *
FROM vw_order_summary
WHERE total_amount > 1500000
ORDER BY total_amount DESC;

-- ─────────────────────────────────────────────────────────────

-- Q44. Using a recursive CTE, list all category hierarchy paths
--      (e.g. Electronics > Phones & Tablets).
-- ANSWER:
WITH RECURSIVE cat_tree AS (
    SELECT category_id, name, parent_id,
           CAST(name AS CHAR(500)) AS path
    FROM categories
    WHERE parent_id IS NULL
    UNION ALL
    SELECT c.category_id, c.name, c.parent_id,
           CONCAT(ct.path, ' > ', c.name)
    FROM categories c
    JOIN cat_tree ct ON ct.category_id = c.parent_id
)
SELECT category_id, name, path
FROM cat_tree
ORDER BY path;

-- ─────────────────────────────────────────────────────────────

-- Q45. Identify the most valuable day of the week for sales.
--      Show weekday name, total orders, and total revenue.
-- ANSWER:
SELECT
    DAYNAME(o.order_date)              AS weekday,
    COUNT(DISTINCT o.order_id)         AS total_orders,
    SUM(oi.quantity * oi.unit_price)   AS total_revenue
FROM orders o
JOIN order_items oi ON oi.order_id = o.order_id
WHERE o.status NOT IN ('cancelled','returned')
GROUP BY DAYOFWEEK(o.order_date), weekday
ORDER BY total_revenue DESC;

-- ─────────────────────────────────────────────────────────────

-- Q46. Write a query to flag orders where the payment amount does NOT match
--      the expected order total (data integrity check).
-- ANSWER:
SELECT
    o.order_id,
    o.status,
    SUM(oi.quantity * oi.unit_price) + o.shipping_fee - o.discount AS expected_amount,
    p.amount                                                          AS paid_amount,
    ABS(
        SUM(oi.quantity * oi.unit_price) + o.shipping_fee - o.discount
        - p.amount
    ) AS discrepancy
FROM orders o
JOIN order_items oi ON oi.order_id  = o.order_id
JOIN payments p     ON p.order_id   = o.order_id
GROUP BY o.order_id, o.status, o.shipping_fee, o.discount, p.amount
HAVING discrepancy > 0.01
ORDER BY discrepancy DESC;

-- ─────────────────────────────────────────────────────────────

-- Q47. For each customer, compute their share of total platform revenue
--      as a percentage, and rank them.
-- ANSWER:
WITH total AS (
    SELECT SUM(oi.quantity * oi.unit_price) AS grand_total
    FROM order_items oi
    JOIN orders o ON o.order_id = oi.order_id
    WHERE o.status NOT IN ('cancelled','returned')
),
cust_rev AS (
    SELECT
        c.customer_id,
        CONCAT(c.first_name,' ',c.last_name)  AS customer_name,
        SUM(oi.quantity * oi.unit_price)       AS revenue
    FROM customers c
    JOIN orders o      ON o.customer_id = c.customer_id
    JOIN order_items oi ON oi.order_id  = o.order_id
    WHERE o.status NOT IN ('cancelled','returned')
    GROUP BY c.customer_id, customer_name
)
SELECT customer_name,
       revenue,
       ROUND(revenue / t.grand_total * 100, 2) AS revenue_share_pct,
       RANK() OVER (ORDER BY revenue DESC)      AS revenue_rank
FROM cust_rev, total t
ORDER BY revenue DESC
LIMIT 20;

-- ─────────────────────────────────────────────────────────────

-- Q48. Write a query to calculate a 3-month rolling average of revenue.
-- ANSWER:
WITH monthly_rev AS (
    SELECT
        DATE_FORMAT(o.order_date,'%Y-%m')    AS month,
        SUM(oi.quantity * oi.unit_price)     AS revenue
    FROM orders o
    JOIN order_items oi ON oi.order_id = o.order_id
    WHERE o.status NOT IN ('cancelled','returned')
    GROUP BY month
)
SELECT
    month,
    revenue,
    ROUND(
        AVG(revenue) OVER (
            ORDER BY month
            ROWS BETWEEN 2 PRECEDING AND CURRENT ROW
        ), 2
    ) AS rolling_3m_avg
FROM monthly_rev
ORDER BY month;

-- ─────────────────────────────────────────────────────────────

-- Q49. Create a stored procedure that generates a customer statement:
--      given a customer_id, list all their orders with totals.
-- ANSWER:
DELIMITER $$
CREATE PROCEDURE GetCustomerStatement(IN p_customer_id INT)
BEGIN
    SELECT
        o.order_id,
        o.order_date,
        o.status,
        COUNT(oi.item_id)              AS line_items,
        SUM(oi.quantity * oi.unit_price) AS subtotal,
        o.shipping_fee,
        o.discount,
        SUM(oi.quantity * oi.unit_price) + o.shipping_fee - o.discount AS total,
        py.method                      AS payment_method,
        py.status                      AS payment_status
    FROM orders o
    JOIN order_items oi ON oi.order_id = o.order_id
    LEFT JOIN payments py ON py.order_id = o.order_id
    WHERE o.customer_id = p_customer_id
    GROUP BY o.order_id, o.order_date, o.status,
             o.shipping_fee, o.discount, py.method, py.status
    ORDER BY o.order_date DESC;
END$$
DELIMITER ;
-- Usage: CALL GetCustomerStatement(1);

-- ─────────────────────────────────────────────────────────────

-- Q50. CAPSTONE — Build a full executive dashboard query:
--      Show KPIs: total revenue, total orders, avg order value,
--      total customers, total products sold, return rate, and
--      top category by revenue — ALL in a single result set.
-- ANSWER:
SELECT
    FORMAT(SUM(oi.quantity * oi.unit_price), 2)     AS total_revenue,
    COUNT(DISTINCT o.order_id)                       AS total_orders,
    FORMAT(SUM(oi.quantity * oi.unit_price)
           / COUNT(DISTINCT o.order_id), 2)          AS avg_order_value,
    (SELECT COUNT(*) FROM customers)                 AS total_customers,
    SUM(oi.quantity)                                 AS total_units_sold,
    ROUND(
        (SELECT COUNT(*) FROM orders WHERE status = 'returned')
        / COUNT(DISTINCT o.order_id) * 100, 2
    )                                                AS return_rate_pct,
    (
        SELECT cat2.name
        FROM categories cat2
        JOIN products p2        ON p2.category_id  = cat2.category_id
        JOIN order_items oi2    ON oi2.product_id  = p2.product_id
        JOIN orders o2          ON o2.order_id     = oi2.order_id
        WHERE o2.status NOT IN ('cancelled','returned')
        GROUP BY cat2.category_id
        ORDER BY SUM(oi2.quantity * oi2.unit_price) DESC
        LIMIT 1
    )                                                AS top_category
FROM orders o
JOIN order_items oi ON oi.order_id = o.order_id
WHERE o.status NOT IN ('cancelled','returned');


-- ════════════════════════════════════════════════════════════
-- QUICK REFERENCE — KEY TABLES & RELATIONSHIPS
-- ════════════════════════════════════════════════════════════
--
--  categories  (category_id, name, parent_id)
--      │
--  products    (product_id, name, category_id, price, cost, stock_qty, brand)
--      │
--  order_items (item_id, order_id, product_id, quantity, unit_price)
--      │                   │
--  orders      (order_id, customer_id, order_date, status, shipping_fee, discount)
--      │                   │
--  payments    (payment_id, order_id, method, status, amount)
--  customers   (customer_id, first_name, last_name, email, city, gender, birthdate)
--  reviews     (review_id, product_id, customer_id, rating, review_text)
--
-- VIEWS:
--  vw_order_summary   — one row per order with customer info and totals
--  vw_product_sales   — sales metrics per product
--
-- ════════════════════════════════════════════════════════════
-- Happy querying!
-- ════════════════════════════════════════════════════════════
